#!/bin/bash
if [ -z "$CMAKE_TOOLCHAIN_FILE" ]; then
	export CMAKE_TOOLCHAIN_FILE=$1
fi
if [ -z "$ROOT" ]; then
	export ROOT=$2
fi

cmake . \
	-DCMAKE_INSTALL_PREFIX="$ROOT" \
	-DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN_FILE" \
	-DENABLE_COMMONCRYPTO=OFF \
	-DENABLE_GNUTLS=OFF \
	-DENABLE_MBEDTLS=OFF \
	-DENABLE_OPENSSL=OFF \
	-DENABLE_WINDOWS_CRYPTO=OFF \
	-DENABLE_BZIP2=OFF \
	-DENABLE_LZMA=OFF \
	-DENABLE_ZSTD=OFF \
	-DBUILD_TOOLS=OFF \
	-DBUILD_REGRESS=OFF \
	-DBUILD_EXAMPLES=OFF \
	-DBUILD_DOC=OFF \
	-DBUILD_SHARED_LIBS=OFF
